### ISSUE TITLE
IncompatibleClassChangeError

### ISSUE THREAD

**Issue by gustavomc** [Lenddo/android-lenddo-onboarding#2]
java.lang.IncompatibleClassChangeError: The method 'com.lenddo.okhttp.Response com.lenddo.okhttp.Call.execute()' was expected to be of type virtual but instead was found to be of type interface (declaration of 'com.lenddo.sdk.http.LenddoOkHttp$LenddoRequestTask'

**Comment by jom16antonio** [comment]
Hi,

It seems you are using both the Lenddo Data SDK and the Lenddo Onboarding SDK in a single application. While this is not yet "officially" supported, it is possible to proceed by using this hack.

First, please try to update the Lenddo Onboarding SDK to the latest commited release.

Then, In your Lenddo Onboarding SDK build.gradle file, kindly change the dependency from:


```xml
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile "com.google.code.gson:gson:2.7"
    compile 'com.squareup.mimecraft:mimecraft:1.1.1'
    compile 'commons-codec:commons-codec:1.10'
    compile 'org.apache.commons:commons-lang3:3.4'
    compile 'com.android.support:support-v4:24.1.1'
}
```


to:
```xml
dependencies {
//    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile "com.google.code.gson:gson:2.7"
    compile 'com.squareup.mimecraft:mimecraft:1.1.1'
    compile 'commons-codec:commons-codec:1.10'
    compile 'org.apache.commons:commons-lang3:3.4'
    compile 'com.android.support:support-v4:24.1.1'
    compile project(':lenddodatasdk')
}
```


This fix will make use of the jar files in the lenddodatasdk modules instead of the jar files included in the onboarding sdk. They are basically the same files, but since they are duplicates. It will cause an issue.

**Comment by gustavomc** [comment]
i dont think it is caused by dependencies, this error is thrown when i execute this line:
```
UIHelper.startVerificationUsingFacebookToken(MyActivity(), myFacebookToken, tokenExpiration, helper);
```

**Comment by jom16antonio** [comment]
HI, Can you please provide a log file so I can trace and replicate the issue. If you could provide a snippet of related codes, that will be helpful as well.

**Comment by Howard3** [comment]
@gustavomc Confirming if you're still having a problem We will be closing the ticket by end of the week if no confirmation there is any trouble. Thanks!

**Comment by gustavomc** [comment]
@Howard3 im still having the issue

@jom16antonio 
this is the log:

```
--------- beginning of crash
09-08 11:43:43.358 23199-30237/com.concredito.express E/AndroidRuntime: FATAL EXCEPTION: pool-10-thread-1
                                                                        Process: com.concredito.express, PID: 23199
                                                                        java.lang.IncompatibleClassChangeError: The method 'com.lenddo.okhttp.Response com.lenddo.okhttp.Call.execute()' was expected to be of type virtual but instead was found to be of type interface (declaration of 'com.lenddo.sdk.http.LenddoOkHttp$LenddoRequestTask' appears in /data/app/com.concredito.express-1/base.apk)
                                                                            at com.lenddo.sdk.http.LenddoOkHttp$LenddoRequestTask.run(LenddoOkHttp.java:120)
                                                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                            at java.lang.Thread.run(Thread.java:818)
```

i have followed your instructions, and the problem continue in this line

```
UIHelper.startVerificationUsingFacebookToken(this.getActivity(), myFacebookToken, tokenExpiration, helper);
```

**Comment by jom16antonio** [comment]
Hi @gustavomc,

How are you generating the client_id for use in the data sdk and onboarding sdk?

In starting the Android Data SDK, we call this code.
```java
AndroidData.startAndroidData(MainActivity.this, clientId);
```

You may try adding this line of code before the startAndroidData() function call and see if this will resolve the issue.
```java
String clientId = "your client id";
LenddoCoreInfo.setCoreInfo(getApplicationContext(), LenddoCoreInfo.COREINFO_CLIENT_ID, clientId);
LenddoCoreInfo.initCoreInfo(getApplicationContext(), "");
AndroidData.startAndroidData(MainActivity.this, clientId);
````

By force calling initCoreInfo before starting the Lenddo Data SDK, it will generate an installation_id for both the Data SDK and the Onboarding SDK. This is assuming that the call to use the data sdk comes first before the call to use the onboarding sdk.

Kindly try the above steps and see if it will resolve the issue with the installation_id.
Hopefully in the future updates, integration of **both** data sdk and onboarding sdk will be easier.

-Joey

**Comment by Howard3** [comment]
Hello @gustavomc following up on this. Please let us know if you're still having issues.

**Comment by gustavomc** [comment]
hi @jom16antonio, @Howard3 
my issue is solved,
thanks for your help.

**Comment by Howard3** [comment]
Great news @gustavomc thank you!
