### ISSUE TITLE
How to resolve PARTNER_CLIENT_ALREADY_PROCESSED error?

### ISSUE THREAD

**Issue by berkedel** [Lenddo/android-lenddo-onboarding#6]
I got the following error below after click the `Submit and Get Verified` button.
```
01-30 14:22:04.576 6305-6462/lenddo.com.lenddoconnect E/com.lenddo.sdk.utils.Utils: postOnboardingSession() onError statusCode:400 rawResponse:{"statusCode":400,"error":"Bad Request","message":"PARTNER_CLIENT_ALREADY_PROCESSED"}
```

My questions are,
* What the `PARTNER_CLIENT_ALREADY_PROCESSED` error means?
* How to resolve this error?

Best regards.

**Comment by jom16antonio** [comment]
Hi @berkedel,

This error response means that you are trying to onboard an "application id" that was already processed or onboarded. Normally, you would only process an onboarding application once. If you are doing some testings, you must provide another _application id_.

Regards,
Joey

**Comment by berkedel** [comment]
Currently I am doing some tests. The *application id* here is a client id?

Btw, is it possible to cancel the onboarding application after sending to the server?

Thank you.

**Comment by jom16antonio** [comment]
Hi,

Yes, application id is the client id. We are transitioning from client_id to application_id.

Hmm, once the application have been sent to server (even partially) it is no longer possible to re-use the application id, as the application id will be associated with any of the onboarded partner social network (Yahoo, LinkedIn, Gmail, Windows Live, or Facebook). Although there is a cancel button during onboarding process per social network. Again, cancelling doesn't always mean the application id can be re-used.

Best Regards.
